on:
  workflow_dispatch:
  push:
    paths-ignore: [README.md]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false

      - name: Build Refs
        if: ${{ steps.version.outputs.version != 'none' }}
        run: |
          bash ./update.sh

      - name: Create Release
        if: ${{ steps.version.outputs.version != 'none' }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          tag: v${{ steps.version.outputs.version }}
          body: |
            Auto Update to v${{ steps.version.outputs.version }}

      - name: Commit & Push changes
        if: ${{ steps.version.outputs.version != 'none' }}
        uses: actions-js/push@master
        with:
          branch: main
          message: "Auto Update to v${{ steps.version.outputs.version }}"
          github_token: ${{ secrets.GITHUB_TOKEN }}
