on:
  schedule:
    - cron: "0 0 * * 0" # Weekly, on Sunday's
  workflow_dispatch:
  push:


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false

      # - name: Check for Updates
      # run: |
      # VERSION=sed -n 's/^VERSION="\([^"]*\)".*/\1/p' ./update.sh

      - name: Auto Update
        id: autoupdate
        run: |
          bash ./update.sh
          sed -n 's/^VERSION="\([^"]*\)".*/\1/p' ./update.sh

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          tag: v${{ steps.autoupdate.outputs.version }}
          body: |
            Auto Update to v${{ steps.autoupdate.outputs.version }}
